### ISSUE TITLE
Support new google design library

### ISSUE THREAD

**Issue by yoavst** [linroid/FilterMenu#11]
Change `<attr name="menu" format="reference"/>` to another name so it would work alongside google design library.

**Comment by yoavst** [comment]
@linroid ?

**Comment by linroid** [comment]
Sorry, I missed the notification.
The attribute is useless currently, so I removed it.

https://github.com/linroid/FilterMenu/commit/a498bd8896782ba6639506f681ba8dc7257b3c2f

**Comment by yoavst** [comment]
Can you upload it to maven?

**Comment by linroid** [comment]
Yes , I had done it, just wait for update
