### ISSUE TITLE
Impossible to build

### ISSUE THREAD

**Issue by sguiheux** [linroid/FilterMenu#13]
\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\values\values.xml
Error:(2) Attribute "primaryColor" has already been defined
Error:Execution failed for task ':app:processDebugResources'.

> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files (x86)\Android\android-sdk\build-tools\21.1.2\aapt.exe'' finished with non-zero exit value 1

It seems that you do not have to use attribut name  primaryColor in attrs.xml

**Comment by linroid** [comment]
I add `fm_` prefix to all custom attributes 6e6f291fbaa4426a86cbc92e4dbe5ebcd038c182

**Comment by sguiheux** [comment]
Thanks I can build my projet now :)
