### ISSUE TITLE
The aar on jcenter may has some problem.

### ISSUE THREAD

**Issue by Ivolian** [linroid/FilterMenu#14]
When i use the aar  on jcenter, something was wrong.
If i use the aar made by the master project, it can be OK.
So i wonder the aar on jcenter may has some problem.

**Comment by linroid** [comment]
hi, i make a project use the aar from jcenter,and it works well, can u tell me more about the errors?

**Comment by Ivolian** [comment]
This problem happened when I use version 0.2.0:
Error:(21) No resource identifier found for attribute 'fm_centerBottom' in package ...
And now i use version 0.2.3，everything is right.

**Comment by linroid** [comment]
:)
