### ISSUE TITLE
Inflate from menu

### ISSUE THREAD

**Issue by alorma** [linroid/FilterMenu#3]
It will be awesome if it can use menu resources.

**Comment by linroid** [comment]
well,it will take me some time to implement it, and I want to support for sub-menu

**Comment by alorma** [comment]
I can help in the first level of menu parser, if i have time, and make a PR

**Comment by linroid** [comment]
That's great, thank u

**Comment by alorma** [comment]
https://github.com/linroid/FilterMenu/pull/4
